/**
 * Standard filter list snapshots from EasyList and EasyPrivacy
 * Compiled for Daps Shield engine (brave/adblock-rust syntax)
 * Hardened for aggressive streaming and pirate websites
 */

export const BUNDLED_EASYLIST_RULES: string[] = [
  // Google AdSense & DoubleClick
  '||googleads.g.doubleclick.net^',
  '||pagead2.googlesyndication.com^',
  '||securepubads.g.doubleclick.net^',
  '||adservice.google.com^',
  '||adservice.google.co.*/adsid/google/ui^',
  '||google-analytics.com/analytics.js',
  '||google-analytics.com/ga.js',
  '||googletagservices.com/tag/js/gpt.js',
  '||stats.g.doubleclick.net^',
  '||ad.doubleclick.net^',
  '||www.googleadservices.com^',
  '||tpc.googlesyndication.com^',
  '||partner.googleadservices.com^',

  // Major Ad Networks (EasyList)
  '||criteo.com^$third-party',
  '||criteo.net^$third-party',
  '||static.criteo.net/js/ld/ld.js',
  '||taboola.com^$third-party',
  '||cdn.taboola.com/libtrc/',
  '||images.taboola.com^',
  '||trc.taboola.com^',
  '||outbrain.com^$third-party',
  '||widgets.outbrain.com/outbrain.js',
  '||images.outbrain.com^',
  '||adnxs.com^$third-party',
  '||ib.adnxs.com^',
  '||rubiconproject.com^$third-party',
  '||optimized-by.rubiconproject.com^',
  '||pubmatic.com^$third-party',
  '||ads.pubmatic.com^',
  '||openx.net^$third-party',
  '||casalemedia.com^$third-party',
  '||advertising.com^$third-party',
  '||bidswitch.net^$third-party',
  '||adform.net^$third-party',
  '||adroll.com^$third-party',
  '||sovrn.com^$third-party',
  '||revcontent.com^$third-party',
  '||servedby.revcontent.com^',
  '||cdn.revcontent.com^',
  '||mgid.com^$third-party',
  '||zergnet.com^$third-party',
  '||speakol.com^$third-party',
  '||amazon-adsystem.com^$third-party',
  '||aax.amazon-adsystem.com^',
  '||yieldmo.com^$third-party',
  '||sharethrough.com^$third-party',
  '||smartadserver.com^$third-party',
  '||appnexus.com^$third-party',

  // Aggressive Pop-up, Pop-under & Pirate Streaming Ad Networks
  '||popads.net^',
  '||popcash.net^',
  '||propellerads.com^',
  '||propush.me^',
  '||exoclick.com^',
  '||exdynsrv.com^',
  '||creative.exdynsrv.com^',
  '||exosrv.com^',
  '||contentabc.com^',
  '||servserv.com^',
  '||adsterra.com^',
  '||hilltopads.net^',
  '||hilltopads.com^',
  '||ad-maven.com^',
  '||yllix.com^',
  '||deloton.com^',
  '||monetag.com^',
  '||richpush.co^',
  '||evadav.com^',
  '||zeropark.com^',
  '||clickadu.com^',
  '||adcash.com^',
  '||onclickperformance.com^',
  '||syndication.exdynsrv.com^',
  '||syndication.exoclick.com^',
  '||trafficstars.com^',
  '||trafficjunky.com^',
  '||trafficjunky.net^',
  '||juicyads.com^',
  '||ero-advertising.com^',
  '||realsrv.com^',
  '||tsyndicate.com^',
  '||etahub.com^',
  '||infolinks.com^',
  '||bidvertiser.com^',
  '||adreactor.com^',
  '||chads2.com^',
  '||adxcore.ch^',
  '||vidoomy.com^',
  '||streamad.net^',
  '||vidverto.io^',
  '||creativecdn.com^',
  '||m2pub.com^',
  '||servedbyadbutler.com^',
  '||directrev.com^',
  '||clicksor.com^',
  '||adbutler.com^',
  '||bet365.com^$third-party',
  '||1xbet.com^$third-party',
  '||melbet.com^$third-party',
  '||parimatch.com^$third-party',
  '||mostbet.com^$third-party',
  '||linebet.com^$third-party',
  '||betwinner.com^$third-party',
  '||ad-delivery.net^',
  '||trafficguard.ai^',
  '||aniview.com^',
  '||spotxchange.com^',
  '||teads.tv^',
  '||smartstream.tv^',
  '||outstream.video^',
  '||playbuzz.com^',
  '||connatix.com^',
  '||anyclip.com^',
  '||springserve.com^',
  '||brightroll.com^',
  '||undertone.com^',
  '||exponential.com^',
  '||media.net^',
  '||yieldlove.com^',
  '||primis.tech^',
  '||vi-serve.com^',
  '||vi-network.com^',
  '||showheroes.com^',
  '||brid.tv^',
  '||voox.tv^',
  '||targetspot.com^',
  '||adtrue.com^',
  '||adkernel.com^',

  // Telemetry & Trackers (EasyPrivacy)
  '||scorecardresearch.com^$third-party',
  '||sb.scorecardresearch.com/beacon.js',
  '||quantserve.com^$third-party',
  '||hotjar.com^$third-party',
  '||static.hotjar.com/c/hotjar-',
  '||crazyegg.com^$third-party',
  '||mouseflow.com^$third-party',
  '||fullstory.com^$third-party',
  '||clarity.ms^$third-party',
  '||www.clarity.ms/tag/',
  '||segment.io^$third-party',
  '||cdn.segment.com/analytics.js/',
  '||api.mixpanel.com^',
  '||cdn.mxpnl.com/libs/mixpanel-2.es5.min.js',
  '||branch.io^$third-party',
  '||appsflyer.com^$third-party',
  '||adjust.com^$third-party',
  '||connect.facebook.net/en_US/fbevents.js',
  '||pixel.facebook.com^',
  '||ads.tiktok.com^$third-party',
  '||analytics.tiktok.com^$third-party',
  '||static.ads-twitter.com/uwt.js',
  '||bat.bing.com^$third-party',

  // Cryptominers & Malware
  '||coinhive.com^',
  '||coin-hive.com^',
  '||jsecoin.com^',
  '||cryptoloot.pro^',
  '||webminepool.com^',

  // Path & Query based patterns
  '/pagead/ads?',
  '/pagead/lvz?',
  '/pagead/show_ads.js',
  '/adservice/ext/',
  '/advertisement/$image',
  '/ad-banner-$image',
  '/banners/*$image,third-party',
  '/adserver/*$script',
  '/popunders/$script',
  '/popads/$script',
  '/clicktrack/$third-party',
  '/direct-link/$third-party',

  // Whitelist / Exception rules (Media & Video Embeds must NEVER be blocked)
  '@@||google.com/search',
  '@@||youtube.com^',
  '@@||youtu.be^',
  '@@||youtube-nocookie.com^',
  '@@||googlevideo.com^',
  '@@||player.vimeo.com^',
  '@@||vimeo.com^',
  '@@||dailymotion.com^',
  '@@||dmcdn.net^',
  '@@||twitch.tv^',
  '@@||streamable.com^',
  '@@||rumble.com^',
  '@@||odysee.com^',
  '@@||bilibili.com^',
  '@@||jwplatform.com^',
  '@@||jwpcdn.com^',
  '@@||brightcove.net^',
  '@@||brightcove.com^',
  '@@||wistia.com^',
  '@@||wistia.net^',
  '@@||kaltura.com^',
  '@@||soundcloud.com^',
  '@@||spotify.com^',
  '@@||vidsrc.me^',
  '@@||vidsrc.to^',
  '@@||vidsrc.net^',
  '@@||vidsrc.in^',
  '@@||vidsrc.pm^',
  '@@||superembed.stream^',
  '@@||streamtape.com^',
  '@@||doodstream.com^',
  '@@||dood.to^',
  '@@||dood.watch^',
  '@@||dood.so^',
  '@@||filemoon.sx^',
  '@@||filemoon.to^',
  '@@||mixdrop.co^',
  '@@||mixdrop.to^',
  '@@||mixdrop.ch^',
  '@@||mp4upload.com^',
  '@@||megacloud.tv^',
  '@@||streamwish.to^',
  '@@||streamwish.com^',
  '@@||vidcloud.co^',
  '@@||rabbitstream.net^',
  '@@||dokicloud.one^',
  '@@||voe.sx^',
  '@@||vidhide.com^',
  '@@||streamembed.com^',
  '@@||2embed.to^',
  '@@||2embed.cc^',
  '@@||upstream.to^',
  '@@||dropload.io^',
  '@@||cloudemb.com^',
  '@@||uqload.com^',
  '@@||uqload.io^',
  '@@||embedrise.com^',
  '@@||smashystream.xyz^',
  '@@||multiembed.mov^',
];

export const BUNDLED_COSMETIC_RULES: string[] = [
  // Google AdSense & DoubleClick
  '##.adsbygoogle',
  '##ins.adsbygoogle',
  '##[id^="google_ads_"]',
  '##iframe[id^="google_ads_"]',
  '##[id*="google_ads_iframe"]',
  '##div[id^="aswift_"]',
  '##iframe[id^="aswift_"]',
  '##iframe[src*="doubleclick.net"]',
  '##iframe[src*="googlesyndication.com"]',
  '##iframe[src*="adservice.google"]',

  // Native Ads & Content Recommendation Widgets
  '##.taboola',
  '##.trc_rbox',
  '##[id^="taboola-"]',
  '##.tbl-feed-container',
  '##.outbrain',
  '##.ob-widget',
  '##[id^="outbrain_"]',
  '##.ob-cards',
  '##.revcontent',
  '##[id^="rc-widget-"]',
  '##.mgid',
  '##[id^="mgid_"]',
  '##.mgbox',
  '##.criteo-ad',
  '##[id^="criteo-"]',

  // Third-party ad iframes
  '##iframe[src*="adnxs.com"]',
  '##iframe[src*="criteo.com"]',
  '##iframe[src*="popads.net"]',
  '##iframe[src*="exoclick.com"]',
  '##iframe[src*="adsterra.com"]',
  '##iframe[src*="propellerads.com"]',
  '##iframe[src*="hilltopads"]',
  '##iframe[src*="monetag.com"]',
  '##iframe[src*="clickadu.com"]',
  '##iframe[src*="adcash.com"]',
  '##iframe[src*="trafficstars.com"]',
  '##iframe[src*="juicyads.com"]',
  '##iframe[src*="vidoomy.com"]',
  '##iframe[src*="m2pub.com"]',
  '##iframe[src*="ad-delivery.net"]',
  '##iframe[src*="bet365.com"]',
  '##iframe[src*="1xbet.com"]',

  // Generic ad blocks
  '##.ad',
  '##.ads',
  '##.advert',
  '##.advertising',
  '##.advertisement',
  '##.ad-banner',
  '##.banner-ad',
  '##.banner_ad',
  '##[class*="banner-ad"]',
  '##[class*="banner_ad"]',
  '##[id*="banner-ad"]',
  '##[id*="banner_ad"]',
  '##.ad-container',
  '##.ads-container',
  '##.ad-wrapper',
  '##.ad-box',
  '##.ad-slot',
  '##.ad-unit',
  '##[class*="ad-slot"]',
  '##[class*="ad-box"]',
  '##[class*="ad-unit"]',
  '##[class*="ad-wrapper"]',
  '##[class*="ad-container"]',
  '##[class*="ads-container"]',
  '##[id^="ad_"]',
  '##[id^="ads_"]',
  '##[id*="-ad-"]',
  '##[id*="_ad_"]',
  '##[class*="sponsored"]',
  '##[class*="promoted"]',
  '##[data-ad]',
  '##[data-ad-unit]',
  '##[data-ad-slot]',
  '##[data-dfp-id]',
  '##[data-native_ad]',
  '##.ad-placeholder',
  '##.native-ad',
  '###ad-container',
  '###advertisement',
  '###adblock-banner',

  // Image & Display Ad Banners
  '##img[src*="tpc.googlesyndication.com"]',
  '##img[src*="doubleclick"]',
  '##img[src*="googleads"]',
  '##img[src*="exdynsrv"]',
  '##img[src*="syndication"]',
  '##img[src*="exoclick"]',
  '##img[src*="adsterra"]',
  '##img[src*="propellerads"]',
  '##img[src*="hilltopads"]',
  '##img[src*="monetag"]',
  '##img[src*="juicyads"]',
  '##img[src*="trafficjunky"]',
  '##img[src*="trafficstars"]',
  '##img[src*="realsrv"]',
  '##img[src*="tsyndicate"]',
  '##img[src*="criteo"]',
  '##img[src*="creativecdn"]',
  '##img[src*="revcontent"]',
  '##img[src*="taboola"]',
  '##img[src*="outbrain"]',
  '##img[src*="mgid"]',
  '##img[src*="zergnet"]',
  '##img[src*="speakol"]',
  '##img[src*="/banners/"]',
  '##img[src*="/ads/"]',
  '##img[alt*="advertisement" i]',
  '##img[alt*="sponsored" i]',
  '##img[class*="ad-image"]',
  '##img[class*="banner-img"]',
  '##img[class*="ad-img"]',
  '##a[href*="bet365"] img',
  '##a[href*="1xbet"] img',
  '##a[href*="melbet"] img',
  '##a[href*="parimatch"] img',
  '##a[href*="mostbet"] img',
  '##a[href*="exoclick"] img',
  '##a[href*="adsterra"] img',
  '##a[href*="popads"] img',
  '##a[href*="propeller"] img',
  '##a[href*="hilltop"] img',
  '##a[href*="clickadu"] img',
  '##a[href*="juicyads"] img',
  '##a[href*="trafficjunky"] img',
  '##a[href*="/adclick"] img',
  '##a[href*="/clicktrack"] img',
  '##a[href*="affiliate"] img',
  '##.banner-image',
  '##.ad-image',
  '##.ad-placement',
  '##.ad-holder',
  '##.leaderboard-ad',
  '##.skyscraper-ad',
  '##.rectangle-ad',
  '##.mrec',
  '##[data-ad-width]',
  '##[data-ad-height]',
  '##[data-ad-format]',

  // Screen takeovers, interstitial popups & overlay modals
  '##.interstitial-wrapper',
  '##.interstitial-ad',
  '##.overlay-ad',
  '##.popup-ad',
  '##.popup-overlay',
  '##.fullscreen-ad',
  '##.modal-ad',
  '##[class*="ad-modal"]',
  '##[id*="ad-modal"]',
  '##[class*="interstitial"]',
  '##[id*="interstitial"]',
  '##[class*="takeover"]',
  '##[id*="takeover"]',
  '##.floating-banner',
  '##.sticky-ad',
  '##.bottom-ad-bar',
  '##.top-ad-bar',
  '##div[class*="ad_wrapper"]',
  '##div[id*="ad_wrapper"]',
  '##[class*="sticky-ad"]',
  '##[id*="sticky-ad"]',
  '##.ad-shield-placeholder',

  // Pirate Video Player Overlays & Click-catchers
  '##.jw-ad-container',
  '##.jw-ads',
  '##.jw-ad-label',
  '##.vidoomy-ad',
  '##.fluid_ad',
  '##.ima-ad-container',
  '##.vpaid-container',
  '##.preroll-blocker',
  '##.vast-blocker',
  '##.click-catcher',
  '###player-overlay',
  '###ad-layer',
  '##.ad-overlay',
  '##.video-ad-overlay',
  '##div[class*="jw-ad-"]',
  '##div[id*="jw-ad-"]',
  '##div[class*="overlay-ad"]',
  '##div[id*="overlay-ad"]',
  '##div[class*="clickjacking"]',
];
